PRMP-454 06 NACK tests
nhsconnect/prm-repo-e2e-tests pull request #187
Opened 2024-08-08 12:30 UTC by bethany-kish-nhs

- split existing repository E2E into multiple files, only new additions are in RepositoryNackTests
- Removed ehrOut DB config
- Added tests for NACK 06 messages

2024-08-08 13:37 UTC, chrisbloe commented on src/test/java/uk/nhs/prm/e2etests/test/repositorye2etest/RepositoryNackTests.java
> +        else assertTrue(outboundMessage.contains(knownNackTypeCode));
if (nackCode.equals("99")) {
            assertTrue(outboundMessage.contains(unknownNackTypeCode));
        } else {
            assertTrue(outboundMessage.contains(knownNackTypeCode));
        }

2024-08-08 13:48 UTC, chrisbloe commented on src/test/java/uk/nhs/prm/e2etests/test/repositorye2etest/RepositoryNackTests.java
> +        String erroneousInboundMessage = this.templatingService.getTemplatedString(EHR_REQUEST, ehrRequestContext);
`this.` not required (x3)

2024-08-08 13:48 UTC, chrisbloe requested changes
Couple of minor comments.

2024-08-14 14:31 UTC, chrisbloe-nhse approved these changes
Happy with the splitting out of the new tests, and version upgrades.

2024-08-14 14:31 UTC, merged