PRMT- 4001 - 20 Health Record Requests in a Minute
nhsconnect/prm-repo-e2e-tests pull request #86
Opened 2023-09-20 14:06 UTC by MohammadIqbalAD-NHS

2023-09-20 14:12 UTC, martin-nhs commented on src/test/java/uk/nhs/prm/e2etests/test/RepositoryE2ETest.java
> +        }
Could potentially do something like this `Stream.generate(UUID.randomUUID().toString()).limit(20).forEach(messageId -> {DO LOGIC HERE});` 😄 forgive me if it's syntactically or programmatically incorrect, just from the top of my head!

2023-09-20 14:45 UTC, MohammadIqbalAD-NHS commented on src/main/java/uk/nhs/prm/e2etests/service/SqsService.java
> +        int ehrFragmentCount = 0;
do you reckon we rename these to `ehrCoreFound `and `ehrFragmentFound ` to be inline with "allMessagesFound" ?

2023-09-20 15:05 UTC, martin-nhs commented on src/test/java/uk/nhs/prm/e2etests/test/RepositoryE2ETest.java
> +        List<String> outboundConversationIds = Stream.generate(() -> (UUID.randomUUID().toString())).limit(20).toList();
Could we break `.limit()` and `.toList()` onto their own lines please?

2023-09-20 15:07 UTC, martin-nhs commented on src/test/java/uk/nhs/prm/e2etests/test/RepositoryE2ETest.java
> +        );
Could we move the `20` and `0` onto a single line please; `outboundConversationIds` optional depending on length!

2023-09-20 15:07 UTC, martin-nhs commented on src/test/java/uk/nhs/prm/e2etests/test/RepositoryE2ETest.java
> +    @Timeout(value = 60, unit = SECONDS)
Great find with this one, will be very useful going forward! 🥳 🎊

2023-09-20 15:09 UTC, martin-nhs commented on src/test/java/uk/nhs/prm/e2etests/test/RepositoryE2ETest.java
> +            mhsInboundQueue.sendMessage(ehrRequestMessage, conversationId);
Could we add `this` please, so that when this class grows in size we're able to directly spot it's reference a member!

2023-09-20 15:11 UTC, martin-nhs requested changes
To optionally address:

https://github.com/nhsconnect/prm-repo-e2e-tests/pull/86#discussion_r1331783185 https://github.com/nhsconnect/prm-repo-e2e-tests/pull/86#discussion_r1331780390 https://github.com/nhsconnect/prm-repo-e2e-tests/pull/86#discussion_r1331777855

Other than this it looks awesome, great job! 😄

2023-09-21 11:06 UTC, martin-nhs approved these changes

2023-09-21 13:43 UTC, merged